
name: ML Model Training Workflow

on:
  push:
    branches:
      - ops
  pull_request:
    branches:
      - ops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train ML Model
      run: python model.py

    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: trained_model.pkl
